In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
data = pd.read_csv('data.csv', sep=';')

/home/raphael/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (22,75) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
pd.set_option('display.max_columns', None)

# Visualização incial do dataset

In [4]:
data.head()

,account.licenseNumber,account.name,imvl_type,listing.acceptExchange,listing.address.city,listing.address.confidence,listing.address.country,listing.address.level,listing.address.neighborhood,listing.address.point.lat,listing.address.point.lon,listing.address.point.source,listing.address.precision,listing.address.state,listing.address.street,listing.address.streetNumber,listing.address.zipCode,listing.address.zone,listing.advertiserId,listing.amenities,listing.backyard,listing.barbgrill,listing.bathrooms,listing.bathtub,listing.bedrooms,listing.businessTypeContext,listing.createdAt,listing.description,listing.displayAddressType,listing.externalId,listing.fireplace,listing.floors,listing.furnished,listing.garden,listing.guestpark,listing.gym,listing.hottub,listing.id,listing.isInactive,listing.legacyId,listing.link,listing.listingType,listing.mountainview,listing.parkingSpaces,listing.partyhall,listing.playground,listing.pool,listing.portal,listing.preview,listing.pricingInfo.businessLabel,listing.pricingInfo.businessType,listing.pricingInfo.isRent,listing.pricingInfo.isSale,listing.pricingInfo.monthlyCondoFee,listing.pricingInfo.period,listing.pricingInfo.price,listing.pricingInfo.rentalPrice,listing.pricingInfo.rentalTotalPrice,listing.pricingInfo.salePrice,listing.pricingInfo.yearlyIptu,listing.propertyType,listing.publicationType,listing.sauna,listing.soundproofing,listing.sportcourt,listing.subtitle,listing.suites,listing.tenniscourt,listing.title,listing.totalAreas,listing.unitFloor,listing.unitSubTypes,listing.unitTypes,listing.unitsOnTheFloor,listing.updatedAt,listing.usableAreas,listing.usageTypes,type
0,04268-J-SP,ADI Assessoria e Imóveis Ltda,apartamentos,False,São Paulo,VALID_STREET,BR,STREET,Parada Inglesa,-23.493796,-46.605705,GOOGLE,GEOMETRIC_CENTER,São Paulo,Rua Manajeru,normal,normal,Zona Norte,7bf57a4f-0a40-781d-c7b0-5af8f92bd22d,normal,False,False,1,False,2,RENTAL,2020-06-17T10:12:05.109Z,LINDO APARTAMENTO PARADA INGLESA<br><br>2 DORM...,ALL,2481,False,normal,False,False,False,False,False,2486576702,False,normal,/imovel/aluguel-apartamento-2-quartos-parada-i...,USED,False,normal,False,False,False,ZAP,False,Alugar,RENTAL,True,False,50,mês,1.3,1.3,1.350,normal,50,UNIT,SUPER_PREMIUM,False,False,False,Apartamento para alugar em,normal,False,SãO PAULO - Apartamento Padrão - Parada Inglesa,45,0,normal,APARTMENT,0,2020-07-24T05:06:08.843Z,45,RESIDENTIAL,superPremium
1,00254-J-SC,San Remos Imóveis,apartamentos,False,Florianópolis,VALID_STREET,BR,STREET,Agronômica,-27.576887,-48.54293,GOOGLE,ROOFTOP,Santa Catarina,Avenida Governador Irineu Bornhausen,3440,88025201,Bairros,4facce12-e20d-00a9-e96c-f0fec9d61fb8,KITCHEN_CABINETS|BUILTIN_WARDROBE|BALCONY|SERV...,False,False,3,False,3,RENTAL,2020-07-10T23:40:26.142Z,EXCELENTE LOCALIZAÇÃO - TRANQUILIDADE E COMODI...,ALL,2060,False,normal,False,False,False,False,False,2489060354,False,normal,/imovel/aluguel-apartamento-3-quartos-com-arma...,USED,False,1,False,False,False,ZAP,False,Alugar,RENTAL,True,False,1.961,mês,3.6,3.6,5.561,normal,370,UNIT,SUPER_PREMIUM,False,False,False,Apartamento para alugar em,1,False,Florianópolis - Apartamento Padrão - Agronômica,140,0,normal,APARTMENT,0,2020-07-12T11:43:29.976Z,140,RESIDENTIAL,superPremium
2,48861-F-RJ,Família Bacellar Imobiliária,apartamentos,False,Rio de Janeiro,VALID_STREET,BR,STREET,Recreio Dos Bandeirantes,-23.018798,-43.462056,GOOGLE,GEOMETRIC_CENTER,Rio de Janeiro,Rua Mário Faustino,normal,22795225,Zona Oeste,99a49079-2e53-2611-c44f-d06c291e8276,ELEVATOR|INTERCOM|KITCHEN_CABINETS|BUILTIN_WAR...,False,False,3,False,3,RENTAL,2020-07-23T21:43:24.010Z,Cód: TIAP32493. Para quem quer morar próximo d...,STREET,TIAP32493,False,normal,False,False,False,False,False,2490399573,False,normal,/imovel/aluguel-apartamento-3-quartos-com-elev...,USED,False,2,False,False,False,ZAP,False,Alugar,RENTAL,True,False,835,mês,2.1,2.1,2.935,normal,244,UNIT,SUPER_PREMIUM,False,False,False,Apartamento para alugar em,1,False,Rio de Janeiro - Apartamento Padrão - Recreio ...,100,0,normal,APARTMENT,0,2020-07-30T03:11:32.521Z,100,RESIDENTIAL,superPremium
3,17452-J-SP,Next Soluções Imobiliárias,apartamentos,False,Campinas,VALID_STREET,BR,STREET,Cambuí,-22.899193,-47.053086,GOOGLE,ROOFTOP,São Paulo,Rua Barreto Leme,1920,13025085,Bairros,eaa31cc0-db78-0b60-6ecf-a917d42f9eee,POOL|SAUNA,False,False,2,False,1,RENTAL,2016-12-12T04:15:29.087Z,Apartamento mobiliado para alugar no Cambuí.<b...,ALL,AP025700,False,normal,False,False,False,False,False,2464055602,False,normal,/imovel/aluguel-apartamento-1-quarto-com-pisci...,USED,False,1,False,False,True,ZAP,False,Alugar,RENTAL,True,False,134.437,mês,3.0,3.0,137.437,normal,90,UNIT,PREMIUM,True,False,False,Apartamento para alugar em,0,False,Campinas - Apartamento Padrão - Cambuí,80,0,normal,APARTMENT,0,2020-07-16T17:15:06.708Z,80,RESIDENTIAL,premium
4,24344-J-SP,QUINTO ANDAR SERVICOS IMOBILIARIOS LTDA,apartamentos,False,São Paulo,VALID_STREET,BR,STREET,Ipiranga,-23.598672,-46.604629,GOOGLE,ROOFTOP,São Paulo,Rua Clemente Pereira,64,04216060,Zona Sul,a8c36aa5-da1c-0c25-7d28-b5e62fed6a80,BARBECUE_GRILL|POOL|ELEVATOR|PLAYGROUND|SPORTS...,False,True,3,False,2,RENTAL,2020-07-28T22:32:55.573Z,"Alugue rápido, sem fiador e com segurança! Age...",ALL,893111543,False,normal,False,False,False,False,False,2490870778,False,normal,/imovel/aluguel-apartamento-2-quartos-com-pisc...,USED,False,2,True,True,True,ZAP,False,Alugar,RENTAL,True,False,536,mês,2.6,2.6,3.136,normal,17,UNIT,PREMIUM,True,False,True,Apartamento para alugar em,2,False,São Paulo - Apartamento Padrão - Ipiranga,69,0,normal,APARTMENT,0,2020-07-29T04:32:26.854Z,69,RESIDENTIAL,premium

In [6]:
#Variavel auxilixar com o número de linhas do dataset
number_of_rows = len(data)

In [7]:
number_of_rows

35772

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35772 entries, 0 to 35771
Data columns (total 61 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   imvl_type                             35772 non-null  object
 1   listing.acceptExchange                35772 non-null  bool
 2   listing.address.city                  35772 non-null  object
 3   listing.address.confidence            35772 non-null  object
 4   listing.address.country               35772 non-null  object
 5   listing.address.level                 35772 non-null  object
 6   listing.address.neighborhood          35772 non-null  object
 7   listing.address.point.lat             35772 non-null  object
 8   listing.address.point.lon             35772 non-null  object
 9   listing.address.state                 35772 non-null  object
 10  listing.address.street                35772 non-null  object
 11  listing.address.streetNumber          35772 non-null  object
 12  listing.address.zipCode               35772 non-null  object
 13  listing.address.zone                  35772 non-null  object
 14  listing.amenities                     35772 non-null  object
 15  listing.backyard                      35772 non-null  bool
 16  listing.barbgrill                     35772 non-null  bool
 17  listing.bathrooms                     35772 non-null  object
 18  listing.bathtub                       35772 non-null  bool
 19  listing.bedrooms                      35772 non-null  int64
 20  listing.businessTypeContext           35772 non-null  object
 21  listing.displayAddressType            35772 non-null  object
 22  listing.fireplace                     35772 non-null  bool
 23  listing.floors                        35772 non-null  object
 24  listing.furnished                     35772 non-null  bool
 25  listing.garden                        35772 non-null  bool
 26  listing.guestpark                     35772 non-null  bool
 27  listing.gym                           35772 non-null  bool
 28  listing.hottub                        35772 non-null  bool
 29  listing.isInactive                    35772 non-null  bool
 30  listing.legacyId                      35772 non-null  object
 31  listing.listingType                   35772 non-null  object
 32  listing.mountainview                  35772 non-null  bool
 33  listing.parkingSpaces                 35772 non-null  object
 34  listing.partyhall                     35772 non-null  bool
 35  listing.playground                    35772 non-null  bool
 36  listing.pool                          35772 non-null  bool
 37  listing.pricingInfo.isRent            35772 non-null  bool
 38  listing.pricingInfo.isSale            35772 non-null  bool
 39  listing.pricingInfo.monthlyCondoFee   35772 non-null  object
 40  listing.pricingInfo.period            35772 non-null  object
 41  listing.pricingInfo.price             35772 non-null  float64
 42  listing.pricingInfo.rentalPrice       35772 non-null  float64
 43  listing.pricingInfo.rentalTotalPrice  35772 non-null  object
 44  listing.pricingInfo.salePrice         35772 non-null  object
 45  listing.pricingInfo.yearlyIptu        35772 non-null  object
 46  listing.propertyType                  35772 non-null  object
 47  listing.publicationType               35772 non-null  object
 48  listing.sauna                         35772 non-null  bool
 49  listing.soundproofing                 35772 non-null  bool
 50  listing.sportcourt                    35772 non-null  bool
 51  listing.suites                        35772 non-null  object
 52  listing.tenniscourt                   35772 non-null  bool
 53  listing.totalAreas                    35772 non-null  object
 54  listing.unitFloor                     35772 non-null  int64
 55  listing.unitSubTypes                  35772 non-null  object
 56  listing.unitTypes                     35772 non-null  object
 57  listing.unitsOnTheFloor               35772 non-null  int64
 58  listing.usableAreas                   35772 non-null  object
 59  listing.usageTypes                    35772 non-null  object
 60  type                                  35772 non-null  object
dtypes: bool(21), float64(2), int64(3), object(35)
memory usage: 11.6+ MB

In [9]:
data.describe()

,listing.bedrooms,listing.pricingInfo.price,listing.pricingInfo.rentalPrice,listing.unitFloor,listing.unitsOnTheFloor
count,35772.000000,35772.000000,35772.000000,35772.000000,35772.000000
mean,2.334116,127.638362,127.638362,0.142514,0.328721
std,1.275377,277.270735,277.270735,1.158915,1.914411
min,0.000000,1.000000,1.000000,0.000000,0.000000
25%,1.000000,1.900000,1.900000,0.000000,0.000000
50%,2.000000,3.500000,3.500000,0.000000,0.000000
75%,3.000000,12.000000,12.000000,0.000000,0.000000
max,14.000000,999.000000,999.000000,29.000000,52.000000

# Limpeza dos dados

## Removendo colunas com informações não importante/interpretáveis

In [ ]:
data.drop(['account.licenseNumber'],axis=1,inplace=True)
data.drop(['account.name'],axis=1,inplace=True)
data.drop(['listing.address.precision'],axis=1,inplace=True)
data.drop(['listing.address.point.source'],axis=1,inplace=True)
data.drop(['listing.advertiserId'],axis=1,inplace=True)
data.drop(['listing.createdAt'],axis=1,inplace=True)
data.drop(['listing.description'],axis=1,inplace=True)
data.drop(['listing.externalId'],axis=1,inplace=True)
data.drop(['listing.id'],axis=1,inplace=True)
data.drop(['listing.link'],axis=1,inplace=True)
data.drop(['listing.portal'],axis=1,inplace=True)
data.drop(['listing.preview'],axis=1,inplace=True)
data.drop(['listing.pricingInfo.businessLabel'],axis=1,inplace=True)
data.drop(['listing.pricingInfo.businessType'],axis=1,inplace=True)
data.drop(['listing.subtitle'],axis=1,inplace=True)
data.drop(['listing.title'],axis=1,inplace=True)
data.drop(['listing.updatedAt'],axis=1,inplace=True)

## Colunas com valores null

segundo o autor do dataset os valores null foram tratados para aparecerem como 'normal'

Primeiramente eu salvei os nomes de colunas que possuiam valor 'normal' e em seguida verifiquei nestas colunas quantos linhas possuiam o valor 'normal'.

In [10]:
def get_sum_null_values():
    #segundo o autor do dataset os valores null foram tratados para aparecerem como 'normal'
    columns_with_null_values = data.columns[data.isin(['normal']).sum(axis=0) > 0].tolist()

    #getting the name and total number of null values per column
    columns_with_null_values_sum = {}
    for column_name in columns_with_null_values:
        columns_with_null_values_sum[column_name] = data[column_name].isin(['normal']).sum(axis=0)
    
    return columns_with_null_values_sum

In [11]:
get_sum_null_values()

{'listing.address.neighborhood': 564,
 'listing.address.point.lat': 138,
 'listing.address.point.lon': 138,
 'listing.address.street': 8876,
 'listing.address.streetNumber': 17051,
 'listing.address.zipCode': 5126,
 'listing.address.zone': 560,
 'listing.amenities': 8638,
 'listing.bathrooms': 3,
 'listing.floors': 33249,
 'listing.legacyId': 32072,
 'listing.parkingSpaces': 2613,
 'listing.pricingInfo.monthlyCondoFee': 11025,
 'listing.pricingInfo.rentalTotalPrice': 11095,
 'listing.pricingInfo.salePrice': 26219,
 'listing.pricingInfo.yearlyIptu': 11328,
 'listing.suites': 7241,
 'listing.totalAreas': 1591,
 'listing.unitSubTypes': 31822,
 'listing.usableAreas': 1,
 'type': 28876}

### Removendo colunas com mais de 70% de valores nulos

In [12]:
columns_to_drop = data.columns[((data.isin(['normal']).sum(axis=0))/number_of_rows) > 0.7].tolist()

In [13]:
columns_to_drop

['listing.floors',
 'listing.legacyId',
 'listing.pricingInfo.salePrice',
 'listing.unitSubTypes',
 'type']

In [14]:
for column_name in columns_to_drop:
    data.drop([column_name],axis=1,inplace=True)

In [15]:
get_sum_null_values()

{'listing.address.neighborhood': 564,
 'listing.address.point.lat': 138,
 'listing.address.point.lon': 138,
 'listing.address.street': 8876,
 'listing.address.streetNumber': 17051,
 'listing.address.zipCode': 5126,
 'listing.address.zone': 560,
 'listing.amenities': 8638,
 'listing.bathrooms': 3,
 'listing.parkingSpaces': 2613,
 'listing.pricingInfo.monthlyCondoFee': 11025,
 'listing.pricingInfo.rentalTotalPrice': 11095,
 'listing.pricingInfo.yearlyIptu': 11328,
 'listing.suites': 7241,
 'listing.totalAreas': 1591,
 'listing.usableAreas': 1}

### Removendo linhas onde existem poucos valores nulos em uma coluna

In [19]:
#pesquisar mais, não está funcionando assim#
data = data[data['listing.address.point.lat'].isin(['normal'])]
data = data[data['listing.address.point.lat'].isin(['normal'])]
data = data[data['listing.bathrooms'].isin(['normal'])]
data = data[data['listing.usableAreas'].isin(['normal'])]